const emojiDictionary = {
  "😃": "Happy",
  "😔": "Sad",
  "😂": "Laughing",
  "😭": "Crying",
  "😷": "Sick",
  "😍": "Hearty Eyes",
  "🤑": "Rich",
  "🤗": "Hugging",
  "😐": "Neutral",
  "😴": "Sleepy",
  "🤔": "Thinking",
  "😜": "Winking",
  "🤩": "Star Struck",
  "😬": "Grimacing",
  "🤤": "Drooling",
  "😌": "Relieved",
  "🙄": "Eye Rolling",
  "🥵": "Hot",
  "🥶": "Cold",
  "🤮": "Vomiting",
  "😵": "Dizzy",
  "🥳": "Partying",
  "😲": "Astonished",
  "😳": "Flushed",
  "🥺": "Pleading",
};

module.exports = { emojiDictionary };